apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8081
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - name: http
      port: 8082
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
spec:
  selector:
    app: commerce-service
  ports:
    - name: http
      port: 8083
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-service
spec:
  selector:
    app: assistant-service
  ports:
    - name: http
      port: 8084
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8086
      targetPort: http
